// export const COLORS = {
//     title: '#1D4ED8',
//     getstartedTitle: 'white',
//     black: 'black',
//     white: 'white',
//     backgroundColor: '#1F1D2B',
//     getstarted: 'white',
//     text:'  ',
//     button: '#1D4ED8',
//     createText: 'white',
//       question:'#8C93B4',
//       innerInput:'white',
//       arrow: 'white',
//       line:'white',
//       proceedtext:'white',
//    proceeder:'#81909D',
//    list: '#4D5D6A',
//    proceedbtn:'#1D4ED8',
//    proceed: '#4D5D6A',
//    inlist: '#4D5D6A',
//    roll:'white',
//     borderText: 'white',
//    inputBackground: '#252836',
//    borderColor2: '#4D5D6A',
//    borderColor: 'white',
//    placeholder: '#80909d83'
//   }

  export const COLORS = {
    backgroundColor: '#F5F5F5',
    white: '#1D4ED8',
    title: '#1D4ED8',
    question:'#4D5D6A',
     roll:'#8C93B4',
    arrow:'#4D5D6A',
    line:'#4D5D6A',
    innerInput: '#4D5D6A',
    proceedbtn:'#1D4ED8',
    proceed: 'hsla(224, 76%, 48%, 0.5)',
    proceedtext:'white',
    proceeder:'white',
    getstarted: 'white',
    getstartedTitle: '#1D4ED8',
    list:'#F4F5F6',
    borderColor2:'#D5D5D5',
    black: '#000',
    text: '#8C93B4',
    inlist: 'white',
    button: '#1D4ED8',
    createText: '#0B2253',
    borderText: '#1D4ED8',
       borderColor: '#1D4ED8',
    inputBackground: '#F2F2F2',
       placeholder: '#80909d83'
  }